package com.ch.dao.second;

import com.ch.dataobject.second.Standard;
import org.springframework.stereotype.Repository;

@Repository
public interface StandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Standard
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    int insert(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Standard
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    int insertSelective(Standard record);

    Standard findNewInformation();

    boolean updateStandardStatus(Long getfId);
}