package com.ch.dataobject.master;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminAccount
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String adminaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPwd
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String adminpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.loginStatus
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer loginstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.loginTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Date logintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminAccount
     *
     * @return the value of admin.adminAccount
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getAdminaccount() {
        return adminaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminAccount
     *
     * @param adminaccount the value for admin.adminAccount
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setAdminaccount(String adminaccount) {
        this.adminaccount = adminaccount == null ? null : adminaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPwd
     *
     * @return the value of admin.adminPwd
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getAdminpwd() {
        return adminpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPwd
     *
     * @param adminpwd the value for admin.adminPwd
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setAdminpwd(String adminpwd) {
        this.adminpwd = adminpwd == null ? null : adminpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.loginStatus
     *
     * @return the value of admin.loginStatus
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getLoginstatus() {
        return loginstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.loginStatus
     *
     * @param loginstatus the value for admin.loginStatus
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setLoginstatus(Integer loginstatus) {
        this.loginstatus = loginstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.loginTime
     *
     * @return the value of admin.loginTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.loginTime
     *
     * @param logintime the value for admin.loginTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "id=" + id +
                ", adminname='" + adminname + '\'' +
                ", adminaccount='" + adminaccount + '\'' +
                ", adminpwd='" + adminpwd + '\'' +
                ", loginstatus=" + loginstatus +
                ", logintime=" + logintime +
                '}';
    }
}