package com.ch.dataobject.master;

import java.util.Date;

public class Berth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.berthTotalCapacity
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Double berthtotalcapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.berthUseCapacity
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Double berthusecapacity;


    //剩余

    private Double remainingweight;


    //百分比Residual percentage

    public Double getRemainingweight() {
        return remainingweight;
    }

    public void setRemainingweight(Double remainingweight) {
        this.remainingweight = remainingweight;
    }

    public Double getResidualpercentage() {
        return residualpercentage;
    }

    public void setResidualpercentage(Double residualpercentage) {
        this.residualpercentage = residualpercentage;
    }

    private Double residualpercentage;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.berthWaitNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer berthwaitnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer status;
    private Integer type;
    private Integer bm;
    private Integer lc;
    private String content;

    public Integer getBm() {
        return bm;
    }

    public void setBm(Integer bm) {
        this.bm = bm;
    }

    public Integer getLc() {
        return lc;
    }

    public void setLc(Integer lc) {
        this.lc = lc;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.isWrite
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer iswrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.isCar
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer iscar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.isStop
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer isstop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berth.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer isdel;

    private Integer downspouting;

    private Integer onoff;

    private String ip;

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Integer getDownspouting() {
        return downspouting;
    }

    public void setDownspouting(Integer downspouting) {
        this.downspouting = downspouting;
    }

    public Integer getOnoff() {
        return onoff;
    }

    public void setOnoff(Integer onoff) {
        this.onoff = onoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.id
     *
     * @return the value of berth.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.id
     *
     * @param id the value for berth.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.berthTotalCapacity
     *
     * @return the value of berth.berthTotalCapacity
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Double getBerthtotalcapacity() {
        return berthtotalcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.berthTotalCapacity
     *
     * @param berthtotalcapacity the value for berth.berthTotalCapacity
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setBerthtotalcapacity(Double berthtotalcapacity) {
        this.berthtotalcapacity = berthtotalcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.berthUseCapacity
     *
     * @return the value of berth.berthUseCapacity
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Double getBerthusecapacity() {
        return berthusecapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.berthUseCapacity
     *
     * @param berthusecapacity the value for berth.berthUseCapacity
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setBerthusecapacity(Double berthusecapacity) {
        this.berthusecapacity = berthusecapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.berthWaitNumber
     *
     * @return the value of berth.berthWaitNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getBerthwaitnumber() {
        return berthwaitnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.berthWaitNumber
     *
     * @param berthwaitnumber the value for berth.berthWaitNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setBerthwaitnumber(Integer berthwaitnumber) {
        this.berthwaitnumber = berthwaitnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.status
     *
     * @return the value of berth.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.status
     *
     * @param status the value for berth.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.isWrite
     *
     * @return the value of berth.isWrite
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIswrite() {
        return iswrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.isWrite
     *
     * @param iswrite the value for berth.isWrite
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIswrite(Integer iswrite) {
        this.iswrite = iswrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.isCar
     *
     * @return the value of berth.isCar
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIscar() {
        return iscar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.isCar
     *
     * @param iscar the value for berth.isCar
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIscar(Integer iscar) {
        this.iscar = iscar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.isStop
     *
     * @return the value of berth.isStop
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIsstop() {
        return isstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.isStop
     *
     * @param isstop the value for berth.isStop
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIsstop(Integer isstop) {
        this.isstop = isstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.createTime
     *
     * @return the value of berth.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.createTime
     *
     * @param createtime the value for berth.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column berth.isdel
     *
     * @return the value of berth.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column berth.isdel
     *
     * @param isdel the value for berth.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}