package com.ch.dataobject.master;

import java.util.Date;

public class Car {

    private int trainNumber;
    private double totalWeight;

    public int getTrainNumber() {
        return trainNumber;
    }

    public void setTrainNumber(int trainNumber) {
        this.trainNumber = trainNumber;
    }

    public double getTotalWeight() {
        return totalWeight;
    }

    public void setTotalWeight(double totalWeight) {
        this.totalWeight = totalWeight;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.institute
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.licensePlateNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String licenseplatenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.vehicleWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Double vehicleweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.institute
     *
     * @return the value of car.institute
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.institute
     *
     * @param institute the value for car.institute
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.licensePlateNumber
     *
     * @return the value of car.licensePlateNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getLicenseplatenumber() {
        return licenseplatenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.licensePlateNumber
     *
     * @param licenseplatenumber the value for car.licensePlateNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setLicenseplatenumber(String licenseplatenumber) {
        this.licenseplatenumber = licenseplatenumber == null ? null : licenseplatenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.vehicleWeight
     *
     * @return the value of car.vehicleWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Double getVehicleweight() {
        return vehicleweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.vehicleWeight
     *
     * @param vehicleweight the value for car.vehicleWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setVehicleweight(Double vehicleweight) {
        this.vehicleweight = vehicleweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.createTime
     *
     * @return the value of car.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.createTime
     *
     * @param createtime the value for car.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.isdel
     *
     * @return the value of car.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.isdel
     *
     * @param isdel the value for car.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}