package com.ch.dataobject.master;

import java.util.Date;

public class ReplaceContainer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replace_container.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replace_container.berthId
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer berthid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replace_container.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replace_container.isSuccess
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer issuccess;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replace_container.id
     *
     * @return the value of replace_container.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replace_container.id
     *
     * @param id the value for replace_container.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replace_container.berthId
     *
     * @return the value of replace_container.berthId
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getBerthid() {
        return berthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replace_container.berthId
     *
     * @param berthid the value for replace_container.berthId
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setBerthid(Integer berthid) {
        this.berthid = berthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replace_container.createTime
     *
     * @return the value of replace_container.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replace_container.createTime
     *
     * @param createtime the value for replace_container.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replace_container.isSuccess
     *
     * @return the value of replace_container.isSuccess
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIssuccess() {
        return issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replace_container.isSuccess
     *
     * @param issuccess the value for replace_container.isSuccess
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIssuccess(Integer issuccess) {
        this.issuccess = issuccess;
    }
}