package com.ch.dataobject.master;

import java.util.Date;

public class StopsOutBound {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stops_outbound.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stops_outbound.inputSerialNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String inputserialnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stops_outbound.institute
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stops_outbound.inputowner
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String inputowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stops_outbound.inputTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Date inputtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stops_outbound.licensePlateNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String licenseplatenumber;
    private Integer ifweighting;
    private Integer ifwaitweight;
    private Integer ifberth;
    private Double totalweight;
    private Double vehicleweight;
    private Double cargoweight;
    private Integer berthnumber;
    private Integer status;
    private String information;
    private Integer isdel;
    private Date createtime;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.id
     *
     * @param id the value for stops_outbound.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.inputSerialNumber
     *
     * @return the value of stops_outbound.inputSerialNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getInputserialnumber() {
        return inputserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.inputSerialNumber
     *
     * @param inputserialnumber the value for stops_outbound.inputSerialNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setInputserialnumber(String inputserialnumber) {
        this.inputserialnumber = inputserialnumber == null ? null : inputserialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.institute
     *
     * @return the value of stops_outbound.institute
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.institute
     *
     * @param institute the value for stops_outbound.institute
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.inputowner
     *
     * @return the value of stops_outbound.inputowner
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getInputowner() {
        return inputowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.inputowner
     *
     * @param inputowner the value for stops_outbound.inputowner
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setInputowner(String inputowner) {
        this.inputowner = inputowner == null ? null : inputowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.inputTime
     *
     * @return the value of stops_outbound.inputTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.inputTime
     *
     * @param inputtime the value for stops_outbound.inputTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.licensePlateNumber
     *
     * @return the value of stops_outbound.licensePlateNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getLicenseplatenumber() {
        return licenseplatenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.licensePlateNumber
     *
     * @param licenseplatenumber the value for stops_outbound.licensePlateNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setLicenseplatenumber(String licenseplatenumber) {
        this.licenseplatenumber = licenseplatenumber == null ? null : licenseplatenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.ifWeighting
     *
     * @return the value of stops_outbound.ifWeighting
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIfweighting() {
        return ifweighting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.ifWeighting
     *
     * @param ifweighting the value for stops_outbound.ifWeighting
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIfweighting(Integer ifweighting) {
        this.ifweighting = ifweighting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.ifWaitWeight
     *
     * @return the value of stops_outbound.ifWaitWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIfwaitweight() {
        return ifwaitweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.ifWaitWeight
     *
     * @param ifwaitweight the value for stops_outbound.ifWaitWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIfwaitweight(Integer ifwaitweight) {
        this.ifwaitweight = ifwaitweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.ifBerth
     *
     * @return the value of stops_outbound.ifBerth
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIfberth() {
        return ifberth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.ifBerth
     *
     * @param ifberth the value for stops_outbound.ifBerth
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIfberth(Integer ifberth) {
        this.ifberth = ifberth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.totalWeight
     *
     * @return the value of stops_outbound.totalWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Double getTotalweight() {
        return totalweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.totalWeight
     *
     * @param totalweight the value for stops_outbound.totalWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setTotalweight(Double totalweight) {
        this.totalweight = totalweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.vehicleWeight
     *
     * @return the value of stops_outbound.vehicleWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Double getVehicleweight() {
        return vehicleweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.vehicleWeight
     *
     * @param vehicleweight the value for stops_outbound.vehicleWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setVehicleweight(Double vehicleweight) {
        this.vehicleweight = vehicleweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.cargoWeight
     *
     * @return the value of stops_outbound.cargoWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Double getCargoweight() {
        return cargoweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.cargoWeight
     *
     * @param cargoweight the value for stops_outbound.cargoWeight
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setCargoweight(Double cargoweight) {
        this.cargoweight = cargoweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.berthNumber
     *
     * @return the value of stops_outbound.berthNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getBerthnumber() {
        return berthnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.berthNumber
     *
     * @param berthnumber the value for stops_outbound.berthNumber
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setBerthnumber(Integer berthnumber) {
        this.berthnumber = berthnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.status
     *
     * @return the value of stops_outbound.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.status
     *
     * @param status the value for stops_outbound.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.information
     *
     * @return the value of stops_outbound.information
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.information
     *
     * @param information the value for stops_outbound.information
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.isdel
     *
     * @return the value of stops_outbound.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.isdel
     *
     * @param isdel the value for stops_outbound.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stops_outbound.createTime
     *
     * @return the value of stops_outbound.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stops_outbound.createTime
     *
     * @param createtime the value for stops_outbound.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}