package com.ch.dataobject.master;

import java.util.Date;

public class VoiceRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_record.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_record.remark
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_record.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_record.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_record.berthId
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer berthid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_record.id
     *
     * @return the value of voice_record.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_record.id
     *
     * @param id the value for voice_record.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_record.remark
     *
     * @return the value of voice_record.remark
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_record.remark
     *
     * @param remark the value for voice_record.remark
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_record.createTime
     *
     * @return the value of voice_record.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_record.createTime
     *
     * @param createtime the value for voice_record.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_record.status
     *
     * @return the value of voice_record.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_record.status
     *
     * @param status the value for voice_record.status
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_record.berthId
     *
     * @return the value of voice_record.berthId
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getBerthid() {
        return berthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_record.berthId
     *
     * @param berthid the value for voice_record.berthId
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setBerthid(Integer berthid) {
        this.berthid = berthid;
    }
}