package com.ch.dataobject.master;

import java.util.Date;

public class VoiceContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_content.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_content.remark
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_content.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_content.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    private Integer isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_content.id
     *
     * @return the value of voice_content.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_content.id
     *
     * @param id the value for voice_content.id
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_content.remark
     *
     * @return the value of voice_content.remark
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_content.remark
     *
     * @param remark the value for voice_content.remark
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_content.createTime
     *
     * @return the value of voice_content.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_content.createTime
     *
     * @param createtime the value for voice_content.createTime
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_content.isdel
     *
     * @return the value of voice_content.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_content.isdel
     *
     * @param isdel the value for voice_content.isdel
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}