package com.ch.dataobject.second;

public class Standard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_ID
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private Long fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_StdNo
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private String fStdno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_CarNo
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private String fCarno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_ProName
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private String fProname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_Driver
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private String fDriver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_Gross
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private Double fGross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_Tare
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private Double fTare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_Net
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private Double fNet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_NetTime
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private String fNettime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Standard.F_YLStr1
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    private String fYlstr1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_ID
     *
     * @return the value of T_Standard.F_ID
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public Long getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_ID
     *
     * @param fId the value for T_Standard.F_ID
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfId(Long fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_StdNo
     *
     * @return the value of T_Standard.F_StdNo
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public String getfStdno() {
        return fStdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_StdNo
     *
     * @param fStdno the value for T_Standard.F_StdNo
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfStdno(String fStdno) {
        this.fStdno = fStdno == null ? null : fStdno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_CarNo
     *
     * @return the value of T_Standard.F_CarNo
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public String getfCarno() {
        return fCarno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_CarNo
     *
     * @param fCarno the value for T_Standard.F_CarNo
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfCarno(String fCarno) {
        this.fCarno = fCarno == null ? null : fCarno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_ProName
     *
     * @return the value of T_Standard.F_ProName
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public String getfProname() {
        return fProname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_ProName
     *
     * @param fProname the value for T_Standard.F_ProName
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfProname(String fProname) {
        this.fProname = fProname == null ? null : fProname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_Driver
     *
     * @return the value of T_Standard.F_Driver
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public String getfDriver() {
        return fDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_Driver
     *
     * @param fDriver the value for T_Standard.F_Driver
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfDriver(String fDriver) {
        this.fDriver = fDriver == null ? null : fDriver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_Gross
     *
     * @return the value of T_Standard.F_Gross
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public Double getfGross() {
        return fGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_Gross
     *
     * @param fGross the value for T_Standard.F_Gross
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfGross(Double fGross) {
        this.fGross = fGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_Tare
     *
     * @return the value of T_Standard.F_Tare
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public Double getfTare() {
        return fTare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_Tare
     *
     * @param fTare the value for T_Standard.F_Tare
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfTare(Double fTare) {
        this.fTare = fTare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_Net
     *
     * @return the value of T_Standard.F_Net
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public Double getfNet() {
        return fNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_Net
     *
     * @param fNet the value for T_Standard.F_Net
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfNet(Double fNet) {
        this.fNet = fNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_NetTime
     *
     * @return the value of T_Standard.F_NetTime
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public String getfNettime() {
        return fNettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_NetTime
     *
     * @param fNettime the value for T_Standard.F_NetTime
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfNettime(String fNettime) {
        this.fNettime = fNettime == null ? null : fNettime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Standard.F_YLStr1
     *
     * @return the value of T_Standard.F_YLStr1
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public String getfYlstr1() {
        return fYlstr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Standard.F_YLStr1
     *
     * @param fYlstr1 the value for T_Standard.F_YLStr1
     *
     * @mbg.generated Wed Dec 04 14:52:39 CST 2019
     */
    public void setfYlstr1(String fYlstr1) {
        this.fYlstr1 = fYlstr1 == null ? null : fYlstr1.trim();
    }
}