package com.ch.dao.master;

import com.ch.dataobject.master.VoiceContent;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface VoiceContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_content
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_content
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    int insert(VoiceContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_content
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    int insertSelective(VoiceContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_content
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    VoiceContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_content
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    int updateByPrimaryKeySelective(VoiceContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_content
     *
     * @mbg.generated Wed Nov 20 16:39:04 CST 2019
     */
    int updateByPrimaryKey(VoiceContent record);

    List<VoiceContent> voiceContentMapper();
}